create table cat_clues(
clue int unsigned not null primary key, 
cve_institucion varchar(20), 
nombre_institucion varchar(50), 
municipio varchar(50), 
localidad varchar(100), 
jurisdiccion varchar(5), 
tipo_establecimiento varchar(30), 
tipologia varchar(50),
nombre_unidad varchar(150),
calle varchar(100), 
tipo_asentamiento varchar(30), 
asentamiento varchar(50),
cp varchar(10), 
referencias varchar(100),
cve_estatus_operacion varchar(30),
rfc varchar(20), 
fecha_construccion date, 
fecha_inicio date, 
cve_unidad_movil_programa varchar(100),
cve_tipo_unidad_movil varchar(50),
cve_tipologia_unidad_movil varchar(50),
cve_nivel_atencion varchar(30), 
cve_estrato_unidad varchar(20),
fecha_ultimo_movimiento date)
